version: "3"
services:
    web:
        container_name: webapp
        build: .
        ports:
            - "8010:80"
        networks:
          - app-tier
    db:
        image: mysql:5.7
        ports:
          - "3306:3306"
        volumes:
          - ./mysql-datavolume:/var/lib/mysql
        environment:
          - MYSQL_ROOT_PASSWORD=root
        networks:
          - app-tier
    phpmyadmin:
        image: phpmyadmin/phpmyadmin
        restart: always
        ports:
            - 8183:80
        environment:
            - MYSQL_USER=root
            - MYSQL_ROOT_PASSWORD=root
        networks:
          - app-tier
    redis:
        image: 'bitnami/redis:latest'
        environment:
          - ALLOW_EMPTY_PASSWORD=yes
        volumes:
            - ./redis-persistence:/bitnami/redis/data
        networks:
          - app-tier
        ports:
          - "6379:6379"
networks:
  app-tier:
    driver: bridge